### ISSUE TITLE
Deprecation message appears without configured option: admin_lte.options.control_sidebar

### ISSUE THREAD

**Issue by j-schumann** [kevinpapst/AdminLTEBundle#39]
Hi, having a problem with default install of this component:

Result: Symfony Toolbar shows one deprecation message:  "The config key admin_lte.options.control_sidebar is deprecated, use admin_lte.control_sidebar instead" after the install of the bundle

Expected Result: No messages at all

Steps to reproduce: 
- composer create-project symfony/website-skeleton .
- add simple default controller
- composer config extra.symfony.allow-contrib true
- composer req "kevinpapst/adminlte-bundle:^2.0"
- toolbar shows deprecation message
- dump()-ing the $config right before the trigger_error() in KevinPapst\AdminLTEBundle\DependencyInjection\AdminLTEExtension results in: http://prntscr.com/lid58u
- so it looks like the control_sidebar options is somewhere automatically added to the config root **and** the options sub-key 
- the problem seems to be DependencyInjection\Configuration.php#L246, if I comment this out everything works fine for me

-> I think the component itself should not produce this error, everybody with correct config will receive it  until they can upgrade to 3.0

Thanks in advance,
JS

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.1.7  |
| AdminLTEBundle  | 2.1.2  |
| Operating System  | Linux  |

Content of config/packages/admin_lte.yaml:
```
admin_lte:
    options:
        skin: skin-blue
        fixed_layout: false
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: false

    knp_menu:
        enable: false

    routes:
        adminlte_welcome: home
        adminlte_login: login
        adminlte_profile: profile
```
