### ISSUE TITLE
AdminLTE: invalid config (prepend): Unrecognized option "button"

### ISSUE THREAD

**Issue by GinesGarcia** [kevinpapst/AdminLTEBundle#72]
Hi,
I'm new with symfony but after playing a bit with it, I decided to test a bit this admin bundle. After creating a new project with "composer create-project symfony/skeleton", I've followed the steps to install this bundle, ending up with the following error:

"Unrecognized option "button" under "admin_lte.theme". Available options are "boxed_layout", "collapsed_sidebar", "control_sidebar", "default_avatar", "fixed_layout", "mini_sidebar", "skin", "widget".

The error appears right after refresh the webpage. I tried updating to 2.1 version when installing the bundle (composer require kevinpapst/adminlte-bundle ^2.1) and the error is no more showed, but nothing appears in the browser (seems to be not correctly installed).

### Debug info

| Component  | Version |
| ------------- | ------------- |
| Symfony version  | 4.2.8  |
| AdminLTEBundle  | master/ bbe650b  |
| Operating System  | Windows (xampp)  |

Thanks a lot for your help,
Ginés.

**Comment by kevinpapst** [comment]
Whats in your logs? How does you config look like?

**Comment by GinesGarcia** [comment]
Hi,
which config file?

about the logs:
```
(1/1)                                     InvalidConfigurationException                                                                  Unrecognized  option "button" under "admin_lte.theme". Available options are  "boxed_layout", "collapsed_sidebar", "control_sidebar",  "default_avatar", "fixed_layout", "mini_sidebar", "skin", "widget".
--
in ArrayNode.php line 331
at ArrayNode->normalizeValue(array('button' => array('type' => 'primary', 'size' => false)))in BaseNode.php line 363
at BaseNode->normalize(array('widget' => array('type' => 'primary', 'bordered' => true, 'collapsible' => false, 'collapsible_title' => 'Collapse', 'removable' => false, 'removable_title' => 'Remove', 'solid' => false, 'use_footer' => true), 'button' => array('type' => 'primary', 'size' => false)))in ArrayNode.php line 296
at ArrayNode->normalizeValue(array('theme' => array('widget' => array('type' => 'primary', 'bordered' => true, 'collapsible' => false, 'collapsible_title' => 'Collapse', 'removable' => false, 'removable_title' => 'Remove', 'solid' => false, 'use_footer' => true), 'button' => array('type' => 'primary', 'size' => false)), 'knp_menu' => array('enable' => false, 'main_menu' => 'adminlte_main', 'breadcrumb_menu' => false), 'routes' => array('adminlte_welcome'  => 'home', 'adminlte_login' => 'login', 'adminlte_login_check'  => 'login_check', 'adminlte_message' => 'message',  'adminlte_messages' => 'messages', 'adminlte_notification' =>  'notification', 'adminlte_notifications' => 'notifications',  'adminlte_task' => 'task', 'adminlte_tasks' => 'tasks',  'adminlte_profile' => 'profile')))in BaseNode.php line 363
at BaseNode->normalize(array('options' => array('default_avatar' => 'bundles/adminlte/images/default_avatar.png', 'skin' => 'skin-blue', 'fixed_layout' => false, 'boxed_layout' => false, 'collapsed_sidebar' => false, 'mini_sidebar' => false), 'theme' => array('widget' => array('type' => 'primary', 'bordered' => true, 'collapsible' => false, 'collapsible_title' => 'Collapse', 'removable' => false, 'removable_title' => 'Remove', 'solid' => false, 'use_footer' => true), 'button' => array('type' => 'primary', 'size' => false)), 'knp_menu' => array('enable' => false, 'main_menu' => 'adminlte_main', 'breadcrumb_menu' => false), 'routes' => array('adminlte_welcome'  => 'home', 'adminlte_login' => 'login', 'adminlte_login_check'  => 'login_check', 'adminlte_message' => 'message',  'adminlte_messages' => 'messages', 'adminlte_notification' =>  'notification', 'adminlte_notifications' => 'notifications',  'adminlte_task' => 'task', 'adminlte_tasks' => 'tasks',  'adminlte_profile' => 'profile')))in Processor.php line 35
at Processor->process(object(ArrayNode), array(array('options' => array('default_avatar' => 'bundles/adminlte/images/default_avatar.png', 'skin' => 'skin-blue', 'fixed_layout' => false, 'boxed_layout' => false, 'collapsed_sidebar' => false, 'mini_sidebar' => false), 'theme' => array('widget' => array('type' => 'primary', 'bordered' => true, 'collapsible' => false, 'collapsible_title' => 'Collapse', 'removable' => false, 'removable_title' => 'Remove', 'solid' => false, 'use_footer' => true), 'button' => array('type' => 'primary', 'size' => false)), 'knp_menu' => array('enable' => false, 'main_menu' => 'adminlte_main', 'breadcrumb_menu' => false), 'routes' => array('adminlte_welcome'  => 'home', 'adminlte_login' => 'login', 'adminlte_login_check'  => 'login_check', 'adminlte_message' => 'message',  'adminlte_messages' => 'messages', 'adminlte_notification' =>  'notification', 'adminlte_notifications' => 'notifications',  'adminlte_task' => 'task', 'adminlte_tasks' => 'tasks',  'adminlte_profile' => 'profile'))))in Processor.php line 52
at Processor->processConfiguration(object(Configuration), array(array('options' => array('default_avatar' => 'bundles/adminlte/images/default_avatar.png', 'skin' => 'skin-blue', 'fixed_layout' => false, 'boxed_layout' => false, 'collapsed_sidebar' => false, 'mini_sidebar' => false), 'theme' => array('widget' => array('type' => 'primary', 'bordered' => true, 'collapsible' => false, 'collapsible_title' => 'Collapse', 'removable' => false, 'removable_title' => 'Remove', 'solid' => false, 'use_footer' => true), 'button' => array('type' => 'primary', 'size' => false)), 'knp_menu' => array('enable' => false, 'main_menu' => 'adminlte_main', 'breadcrumb_menu' => false), 'routes' => array('adminlte_welcome'  => 'home', 'adminlte_login' => 'login', 'adminlte_login_check'  => 'login_check', 'adminlte_message' => 'message',  'adminlte_messages' => 'messages', 'adminlte_notification' =>  'notification', 'adminlte_notifications' => 'notifications',  'adminlte_task' => 'task', 'adminlte_tasks' => 'tasks',  'adminlte_profile' => 'profile'))))in ValidateEnvPlaceholdersPass.php line 84
at ValidateEnvPlaceholdersPass->process(object(ContainerBuilder))in Compiler.php line 95
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 750
at ContainerBuilder->compile()in Kernel.php line 544
at Kernel->initializeContainer()in Kernel.php line 133
at Kernel->boot()in Kernel.php line 193
at Kernel->handle(object(Request))in index.php line 25
```
Those are the traces that appears in the browser, because there is no errors in the apache server logs.

Thanks,
Ginés.

**Comment by kevinpapst** [comment]
I am talking about the bundles configuration.
You misconfigured it `config/packages/admin_lte.yaml` (or simply used a wrong indentation in the YAML file).

Use `bin/console debug:config AdminLTEBundle` to debug the config.
If that fails, check that it looks something like this:
```
admin_lte:
    options:
        default_avatar: build/images/default_avatar.png
        skin: skin-green
        fixed_layout: true
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: true
        control_sidebar: {  }
    theme:
        widget:
            use_footer: false
            type: secondary
            solid: false
            collapsible_title: Collapse
            removable_title: Remove
            bordered: true
            collapsible: false
            removable: false
        button:
            type: primary
            size: false
    routes:
        adminlte_profile: user_profile
        adminlte_welcome: homepage
        adminlte_login: fos_user_security_login
        adminlte_login_check: fos_user_security_check
        adminlte_registration: fos_user_registration_register
        adminlte_password_reset: fos_user_resetting_request
        adminlte_message: message
        adminlte_messages: messages
        adminlte_notification: notification
        adminlte_notifications: notifications
        adminlte_task: task
        adminlte_tasks: tasks
    control_sidebar: {  }
    knp_menu:
        enable: false
        main_menu: adminlte_main
        breadcrumb_menu: false
````

**Comment by GinesGarcia** [comment]
Hi, 
Thanks a lot for your reply. This is my config file:

```
#
# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
admin_lte:
    options:
        # default image for missing user avatar images
        default_avatar: bundles/adminlte/images/default_avatar.png
        # the color skin
        skin: skin-blue
        # if activated, the boxed_layout will be deactivated
        fixed_layout: false
        # boxed layout (true) or full-screen (false)
        boxed_layout: false
        # initial collapsed state of the sidebar
        collapsed_sidebar: false
        # whether the logo collapses or not
        mini_sidebar: false

    theme:
        widget:
            type: 'primary'
            bordered: true
            collapsible: false
            collapsible_title: 'Collapse'
            removable: false
            removable_title: 'Remove'
            solid: false
            use_footer: true
        button:
            type: 'primary'
            size: false

    knp_menu:
        enable: false
        main_menu: adminlte_main
        breadcrumb_menu: false

    routes:
        adminlte_welcome: home
        adminlte_login: login
        adminlte_login_check: login_check
        #adminlte_registration: registration
        #adminlte_password_reset: password_reset
        adminlte_message: message
        adminlte_messages: messages
        adminlte_notification: notification
        adminlte_notifications: notifications
        adminlte_task: task
        adminlte_tasks: tasks
        adminlte_profile: profile
```

which is the default one. 

with the 2.1 version, as I said, I can see the default page of symfony but, when moving to a different end-point (home, login, ...) I'm getting the following error:

```

(2/2)                                     NotFoundHttpException                                                                  No route found for "GET /home"
--
in RouterListener.php line 139
at RouterListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(EventDispatcher))in EventDispatcher.php line 212
at EventDispatcher->doDispatch(array(array(object(DebugHandlersListener), 'configure'), array(object(ValidateRequestListener), 'onKernelRequest'), array(object(SessionListener), 'onKernelRequest'), array(object(RouterListener), 'onKernelRequest'), array(object(ResolveControllerNameSubscriber), 'onKernelRequest'), array(object(LocaleListener), 'onKernelRequest')), 'kernel.request', object(GetResponseEvent))in EventDispatcher.php line 44
at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))in HttpKernel.php line 126
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 67
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 198
at Kernel->handle(object(Request))in index.php line 25
```

Thanks,
Ginés.
